name: Docker Build Hubitat Alarm

on:
  push:
    branches:
      - 'master'
    paths:
      - 'Alarm/**'
    tags:
      - 'v*.*.*'
  workflow_dispatch:


jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./Alarm/
          file: ./Alarm/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/hubitatalarm:latest